
 export { default as ButtonPagination_info} from './ButtonPagination_info'
 export { default as GhStar_repo} from './GhStar_repo'
 export { default as AddStar} from './AddStar'
 export { default as RemoveStar} from './RemoveStar'
 export { default as GhImg_user} from './GhImg_user'
 export { default as UserBestRepo} from './UserBestRepo'
 export { default as AddWrongStar} from './AddWrongStar'
 export { default as GhRepoLanguages_repo} from './GhRepoLanguages_repo'
 export { default as AboutQuery} from './AboutQuery'